plugins: ['jekyll-assets']

title: "UC Santa Cruz Special Events"
email: pio@ucsc.edu
description: >- # this means to ignore newlines until "baseurl:"
  UC Santa Cruz Special Events
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://specialevents.ucsc.edu" # the base hostname & protocol for your site, e.g. https://example.com
twitter_username: ucsantacruz
github_username:  ucsc

# Structure configuration
source: ./source
destination: ./docs

sass:
  sass_dir: _sass

collections:
  events:
    output: true
    permalink: /:collection/:path
    sort_by: order

permalink: pretty
timezone: America/Los_Angeles

future: true


encoding: 'utf-8'

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
