[[redirects]]
  from = "/events/flatte-lecture/"
  to = "https://calendar.ucsc.edu/event/flatte_lecture#.XhkWtS2ZPUJ"
  status = 301
  force = true


[[redirects]]
  from = "/events/bunnett-symposium/"
  to = "https://www.chemistry.ucsc.edu/news-events/events/Bunnett/index.html"
  status = 301
  force = true


[[redirects]]
  from = "/events/sinsheimer-lecture/2014/index.html"
  to = "https://calendar.ucsc.edu/event/2014_robert_l_sinsheimer_distinguished_lecture_in_biology#.Xh0RzS2ZPUI"
  status = 301
  force = true

[[redirects]]
  from = "/events/sinsheimer-lecture/2016/index.html"
  to = "https://calendar.ucsc.edu/event/2016_robert_l_sinsheimer_distinguished_lecture_in_biology#.Xh0Rmi2ZPUI"
  status = 301
  force = true

[[redirects]]
  from = "/events/morton-marcus/"
  to = "https://thi.ucsc.edu/projects/morton-marcus-poetry-reading/"
  status = 301
  force = true


[[redirects]]
  from = "/events/faculty-research/"
  to = "https://senate.ucsc.edu/committees/cfrl-committee-on-faculty-research-lecture/index.html"
  status = 301
  force = true

[[redirects]]
  from = "/events/noel-king/"
  to = "https://merrill.ucsc.edu/history/nqk-history/nqking-lecture/index.html"
  status = 301
  force = true

[[redirects]]
  from = "/events/emeriti-lectures/"
  to = "https://emeriti.ucsc.edu/History/Past%20Emeriti%20Lectures.html"
  status = 301
  force = true

[[redirects]]
  from = "/events/maitra/2020/index.html"
  to = "https://thi.ucsc.edu/event/amitav-ghosh-maitra-lecture/"
  status = 301
  force = true


[[redirects]]
  from = "/events/alumniweekend/2020/index.html"
  to = "https://alumniweekend.ucsc.edu"
  status = 301
  force = true


[[redirects]]
  from = "/events/alumniweekend/2020/"
  to = "https://alumniweekend.ucsc.edu"
  status = 301
  force = true

[[redirects]]
  from = "/events/peggy-downes/2020/"
  to = "https://alumniweekend.ucsc.edu/atwood/"
  status = 301
  force = true

[[redirects]]
  from = "/universe-in-verse/index.html"
  to = "/events/universe-in-verse/2020/"
  status = 301
  force = true

[[redirects]]
  from = "/mlk/index.html"
  to = "/events/mlk/2020/"
  status = 301
  force = true

[[redirects]]
  from = "/kraw-lecture/index.html"
  to = "/events/kraw-lecture/2020/"
  status = 301
  force = true

[[redirects]]
  from = "/events/deep-read/2020/"
  to = "https://thi.ucsc.edu/deepread/"
  status = 301
  force = true

[[redirects]]
  from = "/events/50th/index"
  to = "http://50years.ucsc.edu"
  status = 301
  force = true

[[redirects]]
  from = "/events/50th/"
  to = "http://50years.ucsc.edu"
  status = 301
  force = true

[[redirects]]
  from = "/events/peggy-downes/2011/"
  to = "https://thi.ucsc.edu/event/the-peggy-downes-baskin-ethics-lecture-3/"
  status = 301
  force = true

[[redirects]]
  from = "/events/peggy-downes/2014/"
  to = "https://thi.ucsc.edu/toni-morrison-and-angela-davis-on-friendship-and-creativity/"
  status = 301
  force = true

[[redirects]]
  from = "/events/peggy-downes/2016/"
  to = "https://thi.ucsc.edu/2016-baskin-ethics-lecture-fania-davis/"
  status = 301
  force = true

[[redirects]]
  from = "/events/peggy-downes/2018/"
  to = "https://thi.ucsc.edu/2018-baskin-ethics-lecture-alumni-weekend-keynote-the-ethical-role-of-the-public-university/"
  status = 301
  force = true

[[redirects]]
  from = "/events/peggy-downes/2018-2/"
  to = "https://thi.ucsc.edu/jaron-lanier-how-the-internet-failed-and-how-to-recreate-it/"
  status = 301
  force = true

[[redirects]]
  from = "/events/laser/"
  to = "https://ias.ucsc.edu/events/laser"
  status = 301
  force = true

[[redirects]]
  from = "/events/alumniweekend/2015/"
  to = "http://50years.ucsc.edu/alumniweekend2015"
  status = 301
  force = true

[[redirects]]
  from = "/events/alumniweekend/2016/"
  to = "https://alumni.ucsc.edu/alumniweekend/2016/index.html"
  status = 301
  force = true
