[[redirects]]
  from = "/events/flatte-lecture/"
  to = "https://calendar.ucsc.edu/event/flatte_lecture#.XhkWtS2ZPUJ"
  status = 301


  [[redirects]]
  from = "/events/bunnett-symposium/"
  to = "https://www.chemistry.ucsc.edu/news-events/events/Bunnett/index.html"
  status = 301
