[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' 'unsafe-eval' data: *.ucsc.edu *.google-analytics.com ajax.googleapis.com *.googletagmanager.com use.fontawesome.com *.google.com *.netlify.com *.unpkg.com fonts.googleapis.com fonts.gstatic.com unpkg.com *.fontawesome.com visualizedata.ucop.edu *.cloudfront.net *.cloudflare.com fonts.gstatic.com siteimproveanalytics.com; frame-src 'self' *.youtube.com *.google.com visualizedata.ucop.edu;object-src 'none';frame-ancestors 'self' *.google.com *.youtube.com;"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    X-Frame-Options = "DENY"
[[redirects]]
  from = "/events/flatte-lecture/"
  to = "https://calendar.ucsc.edu/event/flatte_lecture#.XhkWtS2ZPUJ"
  status = 301
  force = true
[[redirects]]
  from = "/events/bunnett-symposium/"
  to = "https://www.chemistry.ucsc.edu/news-events/events/Bunnett/index.html"
  status = 301
  force = true
[[redirects]]
  from = "/events/sinsheimer-lecture/2014/index.html"
  to = "https://calendar.ucsc.edu/event/2014_robert_l_sinsheimer_distinguished_lecture_in_biology#.Xh0RzS2ZPUI"
  status = 301
  force = true
[[redirects]]
  from = "/events/sinsheimer-lecture/2016/index.html"
  to = "https://calendar.ucsc.edu/event/2016_robert_l_sinsheimer_distinguished_lecture_in_biology#.Xh0Rmi2ZPUI"
  status = 301
  force = true
[[redirects]]
  from = "/events/morton-marcus/"
  to = "https://thi.ucsc.edu/projects/morton-marcus-poetry-reading/"
  status = 301
  force = true
[[redirects]]
  from = "/events/faculty-research/"
  to = "https://senate.ucsc.edu/committees/cfrl-committee-on-faculty-research-lecture/index.html"
  status = 301
  force = true
[[redirects]]
  from = "/events/noel-king/"
  to = "https://merrill.ucsc.edu/history/nqk-history/nqking-lecture/index.html"
  status = 301
  force = true
[[redirects]]
  from = "/events/emeriti-lectures/"
  to = "https://emeriti.ucsc.edu/History/Past%20Emeriti%20Lectures.html"
  status = 301
  force = true
[[redirects]]
  from = "/events/maitra/2020/"
  to = "https://thi.ucsc.edu/event/amitav-ghosh-maitra-lecture/"
  status = 301
  force = true
[[redirects]]
  from = "/events/alumniweekend/2021/"
  to = "https://alumniweekend.ucsc.edu"
  status = 301
  force = true
[[redirects]]
  from = "/events/alumniweekend/2020/"
  to = "https://alumniweekend.ucsc.edu"
  status = 301
  force = true
[[redirects]]
  from = "/events/peggy-downes/2020/"
  to = "https://alumniweekend.ucsc.edu/atwood/"
  status = 301
  force = true
[[redirects]]
  from = "/universe-in-verse/index.html"
  to = "/events/universe-in-verse/2020/"
  status = 301
  force = true
[[redirects]]
  from = "/mlk/index.html"
  to = "/events/mlk/2020/"
  status = 301
  force = true
[[redirects]]
  from = "/kraw-lecture/index.html"
  to = "/events/kraw-lecture/2020/"
  status = 301
  force = true
[[redirects]]
  from = "/events/deep-read/2020/"
  to = "https://thi.ucsc.edu/deepread/"
  status = 301
  force = true
[[redirects]]
  from = "/events/50th/index"
  to = "http://50years.ucsc.edu"
  status = 301
  force = true
[[redirects]]
  from = "/events/50th/"
  to = "http://50years.ucsc.edu"
  status = 301
  force = true
[[redirects]]
  from = "/events/peggy-downes/2011/"
  to = "https://thi.ucsc.edu/event/the-peggy-downes-baskin-ethics-lecture-3/"
  status = 301
  force = true
[[redirects]]
  from = "/events/peggy-downes/2014/"
  to = "https://thi.ucsc.edu/toni-morrison-and-angela-davis-on-friendship-and-creativity/"
  status = 301
  force = true
[[redirects]]
  from = "/events/peggy-downes/2016/"
  to = "https://thi.ucsc.edu/2016-baskin-ethics-lecture-fania-davis/"
  status = 301
  force = true
[[redirects]]
  from = "/events/peggy-downes/2018/"
  to = "https://thi.ucsc.edu/2018-baskin-ethics-lecture-alumni-weekend-keynote-the-ethical-role-of-the-public-university/"
  status = 301
  force = true
[[redirects]]
  from = "/events/peggy-downes/2018-2/"
  to = "https://thi.ucsc.edu/jaron-lanier-how-the-internet-failed-and-how-to-recreate-it/"
  status = 301
  force = true
[[redirects]]
  from = "/events/laser/2020/"
  to = "https://ias.ucsc.edu/events/2020/laser-talks-october-13-2020"
  status = 301
  force = true
[[redirects]]
  from = "/events/alumniweekend/2015/"
  to = "http://50years.ucsc.edu/alumniweekend2015"
  status = 301
  force = true
[[redirects]]
  from = "/events/alumniweekend/2016/"
  to = "https://alumni.ucsc.edu/alumniweekend/2016/index.html"
  status = 301
  force = true
[[redirects]]
  from = "/events/founders/2015/"
  to = "http://50years.ucsc.edu/founders/"
  status = 301
  force = true
[[redirects]]
  from = "/mlk*"
  to = "/events/mlk"
  status = 301
  force = true
[[redirects]]
  from = "/founders"
  to = "/events/founders"
  status = 301
  force = true
[[redirects]]
  from = "/founders/*"
  to = "/events/founders"
  status = 301
  force = true
[[redirects]]
  from = "/kraw-lecture"
  to = "/events/kraw-lecture"
  status = 301
  force = true
[[redirects]]
  from = "/commencement/"
  to = "https://commencement.ucsc.edu"
  status = 301
  force = true
[[redirects]]
  from = "/universe-in-verse"
  to = "/events/universe-in-verse/2020/"
  status = 301
  force = true
[[redirects]]
  from = "/casfs-fifty/index.html"
  to = "/events/farmtofork/2017/"
  status = 301
  force = true
[[redirects]]
  from = "/farmtofork/"
  to = "/events/farmtofork/"
  status = 301
  force = true
[[redirects]]
  from = "/commencement/2011/"
  to = "/events/commencement/2011/"
  status = 301
  force = true
[[redirects]]
  from = "/commencement/2012/"
  to = "/events/commencement/2012/"
  status = 301
  force = true
[[redirects]]
  from = "/commencement/2013/"
  to = "/events/commencement/2013/"
  status = 301
  force = true
[[redirects]]
  from = "/commencement/2013/"
  to = "/events/commencement/2013/"
  status = 301
  force = true
[[redirects]]
  from = "/commencement/2014/"
  to = "/events/commencement/2014/"
  status = 301
  force = true
[[redirects]]
  from = "/commencement/2015/"
  to = "/events/commencement/2015/"
  status = 301
  force = true
[[redirects]]
  from = "/commencement/2016/"
  to = "/events/commencement/2016/"
  status = 301
  force = true
[[redirects]]
  from = "/commencement/2017/"
  to = "/events/commencement/2017/"
  status = 301
  force = true
[[redirects]]
  from = "/commencement/2018/"
  to = "/events/commencement/2018/"
  status = 301
  force = true
[[redirects]]
  from = "/commencement/2019/"
  to = "/events/commencement/2019/"
  status = 301
  force = true
[[redirects]]
  from = "/livinglegends/"
  to = "/events/livinglegends/"
  status = 301
  force = true
[[redirects]]
  from = "/livinglegends/2017/"
  to = "/events/livinglegends/2017/"
  status = 301
  force = true
[[redirects]]
  from = "/maitra/"
  to = "/events/maitra/"
  status = 301
  force = true
[[redirects]]
  from = "/maitra/2016/"
  to = "/events/maitra/2016/"
  status = 301
  force = true
[[redirects]]
  from = "/maitra/2014/"
  to = "/events/maitra/2014/"
  status = 301
  force = true
[[redirects]]
  from = "/maitra/2013/"
  to = "/events/maitra/2013/"
  status = 301
  force = true
[[redirects]]
  from = "/events/slugs-steins/2020/"
  to = "https://alumni.ucsc.edu/events/regional-events/2020/12/december-slugs-and-steins.html"
  status = 301
  force = true
[[redirects]]
  from = "/events/slugs-steins/2021/"
  to = "hhttps://alumni.ucsc.edu/events/regional-events/2021/03/march-slugs-and-steins.html"
  status = 301
  force = true
[[redirects]]
  from = "/events/atwood/2020/"
  to = "https://thi.ucsc.edu/the-deep-read-margaret-atwood-live-september-22/"
  status = 301
  force = true
[[redirects]]
  from = "/events/election-series/2020/"
  to = "https://transform.ucsc.edu/election-series/"
  status = 301
  force = true
[[redirects]]
  from = "/events/ias/2020/"
  to = "https://ias.ucsc.edu/events/2020/visuality-and-carceral-formations-nicole-fleetwood-herman-gray-nicholas-mirzoeff"
  status = 301
  force = true
[[redirects]]
  from = "/events/morton-marcus/2020/"
  to = "https://thi.ucsc.edu/event/virtual-morgan-parker-morton-marcus-poetry-reading/"
  status = 301
  force = true
[[redirects]]
  from = "/events/water-dancer/2020/"
  to = "https://www.bookshopsantacruz.com/waterdancer"
  status = 301
  force = true
[[redirects]]
  from = "/events/frayed-democracy/2020/"
  to = "https://ucsc.zoom.us/webinar/register/WN_lXQ-eMJwTkuzsPTwtY-uHg"
  status = 301
  force = true
[[redirects]]
  from = "/events/global-crisis/2021/"
  to = "https://calendar.ucsc.edu/event/an_evening_with_jennifer_brea_and_megan_moodie_talking_about_chronic_illness_care_and_covid#.X9PS1i9h3OR"
  status = 301
  force = true
[[redirects]]
  from = "/events/ias/2021/"
  to = "https://ias.ucsc.edu/events/2020/prisons-and-poetics-reginald-dwayne-betts-january-26-2021"
  status = 301
  force = true
[[redirects]]
  from = "/events/beyond/2021/"
  to = "https://beyond.ucsc.edu/2020/12/07/nick-estes-melanie-k-yazzie/"
  status = 301
  force = true
[[redirects]]
  from = "/events/noel-king/2021/"
  to = "https://ucsc.zoom.us/webinar/register/WN_1Rg406OsRVeH_BysLCjBtA"
  status = 301
  force = true
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
